#
# This file is part of Land Cover Classification System Database Model.
# Copyright (C) 2019-2020 INPE.
#
# Land Cover Classification System Database Model is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

language: python

os: linux

cache:
    directories:
        - $HOME/.cache/pip

git:
    quiet: true
    submodules: false

branches:
    only:
        - master
        - /^b-\d+\.\d+\.\d+/

dist: bionic

services:
    - docker

python:
    - 3.7

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls
